### ISSUE TITLE
beta 4

### ISSUE THREAD

**Issue by ricardomga** [nijel/tesseract-ocr-build#1]
Hello, thank you for the great work!!!

Please add support for [beta4](https://github.com/tesseract-ocr/tesseract/releases/tag/4.0.0-beta.4)

Best regards

**Comment by nijel** [comment]
It's now there: https://github.com/nijel/tesseract-ocr-build/releases/tag/4.0.0-beta.4-1

Good to see somebody is actually using this ;-).

**Comment by ricardomga** [comment]
thank you 👍
